[project]
name = "hospital"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.26.0",
    "psycopg[binary]>=3.2.0",
    "pydantic[email]>=2.12.5",
    "python-dotenv>=1.2.1",
]
